AllCops:
  TargetRubyVersion: 2.7
  Exclude:
  - vendor/**/*
  - bin/**/*
  - gemfiles/**/*
  - tmp/**/*
  - db/seeds.rb
  - exe/**/*
  SuggestExtensions: false

### Bundler ###
# Allow gems to be grouped by purpose
Bundler/OrderedGems:
  Enabled: false

### Gems ###
# Allow gems to be grouped by purpose
Gemspec/DateAssignment:
  Enabled: true

Gemspec/OrderedDependencies:
  Enabled: false

### Layout ###
Layout/BeginEndAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Max: 378

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

# see: https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
  - spec/**/*

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/EmptyInPattern:
  Enabled: true
  AllowComments: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SymbolConversion:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: true

### Metrics ###

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 150
  Exclude:
  - spec/**/*

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 19

Metrics/MethodLength:
  Max: 59

Metrics/PerceivedComplexity:
  Max: 41

### Naming ###

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

### Style ###

Style/AccessorGrouping:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: false

Style/ArrayCoercion:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/CombinableLoops:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EndlessMethod:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: false

Style/InPatternThen:
  Enabled: true

Style/InverseMethods:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIf:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NilLambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
  MinDigits: 7

Style/NumericPredicate:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/QuotedSymbols:
  Enabled: true

Style/RandomWithOffset:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/**/*

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringChars:
  Enabled: false

Style/StringConcatenation:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SymbolProc:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
