version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  checks:
    docker:
      - image: circleci/ruby:2.7.4
    steps:
      - checkout
      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "tilt-json_factory.gemspec" }}

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle config gem.givve.io ${PRIVATE_GEM_SERVER_USER}:${PRIVATE_GEM_SERVER_PASS} && bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: gem-cache-v1-{{ checksum "tilt-json_factory.gemspec" }}
          paths:
            - vendor/bundle
      - ruby/rubocop-check
    
  run_specs:
    parameters:
      docker_image:
        type: string
    docker:
      - image: circleci/<< parameters.docker_image >>
    steps:
      - checkout
      - run:                                                                    
          name: Setup CodeClimate Test Reporter                                 
          command: |                                                            
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter                                         
      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "tilt-json_factory.gemspec" }}

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle config gem.givve.io ${PRIVATE_GEM_SERVER_USER}:${PRIVATE_GEM_SERVER_PASS} && bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: gem-cache-v1-{{ checksum "tilt-json_factory.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rspec
          command: |                                                            
            # ./cc-test-reporter before-build                                     
            bundle exec rspec                                                   
            # ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_artifacts:
          path: coverage

workflows:
  all_jobs:
    jobs:
      - checks:
          context: 
          - givve_gem_server
      - run_specs:
          context:
            - givve_gem_server
          matrix:
            parameters:
              docker_image: 
                - ruby:2.7.3
                - ruby:2.7.4
                - ruby:3.0.2
