version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/ruby:2.6.3-stretch # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Install bundler v2
          command: gem install bundler --version=2.0.1

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "tilt-json_factory.gemspec" }}
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle config gem.givve.io ${PRIVATE_GEM_SERVER_USER}:${PRIVATE_GEM_SERVER_PASS} && bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: gem-cache-v1-{{ checksum "tilt-json_factory.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run rspec
          command: bundle exec rspec
      - store_artifacts:
          path: coverage
